### ISSUE TITLE
typescript compile error for version 3.1.0

### ISSUE THREAD

**Issue by yskeat** [RemoteMetering/geteventstore-promise#70]
I hit below error when I try to compile my project in typescript after I update geteventstore-promise version to 3.1.0
```
node_modules/geteventstore-promise/index.d.ts:82:18 - error TS2430: Interface 'TCPReadResult' incorrectly extends interface 'StreamEventsSlice'.
  Types of property 'events' are incompatible.
    Type 'Event[]' is not assignable to type 'ResolvedEvent[]'.
      Type 'Event' is missing the following properties from type 'ResolvedEvent': isResolved, originalStreamId, originalEventNumber

82 export interface TCPReadResult extends StreamEventsSlice {
```

**Comment by mmuller99** [comment]
Hi @yskeat , thanks for logging the issue.  It has been resolved in 3.1.1
